fishcollector/fishcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

fishcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    # http://localhost:8000
    path('', views.home, name="home"),

    #http://localhost:8000/about-us
    path('about-us/', views.about_us, name='about_us'),

    #http://localhost:8000/fish
    path('fish/', views.fish_index, name='index'),

    #http://localhost:8000/fish/1
    path('fish/<int:fish_id>/', views.fish_detail, name='detail'), 

    # http://localhost:8000/fish/create/
    path('fish/create/', views.FishCreate.as_view(), name='fish_create'), 

    # http://localhost:8000/fish/1/update
    path('fish/<int:pk>/update/', views.FishUpdate.as_view(), name='fish_update'),

    # http://localhost:8000/fish/1/delete
    path('fish/<int:pk>/>delete/', views.FishDelete.as_view(), name='fish_delete'),

    # http://localhost:8000/fish/1/add_survey/
    path('fish/<int:fish_id>/add_survey/', views.add_survey, name="add_survey"),

    # http://localhost:8000/fish/1/assoc_collector/1/
    path('fish/<int:fish_id>/assoc_collector/<int:collector_id>/', views.assoc_collector, name='assoc_collector'),

    # http://localhost:8000/collectors/
    path('collectors/', views.CollectorList.as_view(), name='collectors_index'),

    # http://localhost:8000/collectors/1/
    path('collectors/<int:pk>/', views.CollectorDetail.as_view(), name='collectors_detail'),

    # http://localhost:8000/collectors/create/
    path('collectors/create/', views.CollectorCreate.as_view(), name='collectors_create'),

    # http://localhost:8000/collectors/1/update/
    path('collectors/<int:pk>/update/', views.CollectorUpdate.as_view(), name='collectors_update'),
    
    # http://localhost:8000/collectors/1/delete/
    path('collectors/<int:pk>/delete/', views.CollectorDelete.as_view(), name='collectors_delete'),
]

fishcollector/main_app/models.py
from django.db import models
from django.urls import reverse

#used for dropdown menu
AGE = (
    ('L', 'Larval'),
    ('J', 'Juvenile'),
    ('S', 'Subadult'),
    ('A', 'Adult')
)

class Collector(models.Model):
    name = models.CharField(max_length=50)
    vessel = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('collectors_detail', kwargs={'pk': self.id})

class Fish(models.Model):
    commonName = models.CharField(max_length=100)
    sciName = models.CharField(max_length=100)
    habitat = models.TextField(max_length=250)
    quantity = models.IntegerField()

    collectors = models.ManyToManyField(Collector)

#allows us to see the fish name, rather than fish object
    def __str__(self):
        return self.commonName

class Surveys(models.Model):
    date = models.DateField() 
    age = models.CharField(
        max_length=1,
        choices=AGE, #add the choices field option
        default=AGE[3][0] #set default value to A
    )

    fish = models.ForeignKey(Fish, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_age_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

fishcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Surveys

class SurveyForm(ModelForm):
    class Meta:
        model = Surveys
        fields = ['date', 'age']

fishcollector/main_app/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Fish, Collector
from .forms import SurveyForm
# from django.http import HttpResponse

def home(request):
    return render(request, 'home.html')

def about_us(request):
    return render(request, 'about.html')

def fish_index(request):
    fish = Fish.objects.all()
    return render(request, 'fish/index.html', {'fish':fish})

def fish_detail(request, fish_id):
    fish = Fish.objects.get(id=fish_id)
    collectors_fish_doesnt_have = Collector.objects.exclude(id__in = fish.collectors.all().values_list('id'))
    survey_form = SurveyForm()
    return render(
        request, 
        'fish/detail.html', 
        {'fish':fish , 'survey_form':survey_form, 'collectors': collectors_fish_doesnt_have}
    )

def add_survey(request, fish_id):
    #print(request.POST['date']) <-- this allows us to see what's been entered into the form. the request.
    form = SurveyForm(request.POST)
    if form.is_valid():
        new_survey = form.save(commit=False) #commit=False because we need to assign a cat id
        new_survey.fish_id = fish_id # cat_id coming from url
        new_survey.save()    
    return redirect('detail', fish_id=fish_id)


class FishCreate(CreateView):
    model = Fish
    fields = ['commonName', 'sciName', 'habitat', 'quantity']
    # fields = ['age', 'description'] - use this if you want to specify what the form asks for

    def get_success_url(self, **kwargs):
        return reverse('detail', args=(self.object.id, ))

class FishUpdate(UpdateView):
    model = Fish
    fields = '__all__'

    def get_success_url(self, **kwargs):
        return reverse('detail', args=(self.object.id, ))

class FishDelete(DeleteView):
    model = Fish
    success_url = '/fish/'

class CollectorList(ListView):
    model = Collector

class CollectorDetail(DetailView):
    model = Collector

class CollectorCreate(CreateView):
    model = Collector
    fields = '__all__'

class CollectorUpdate(UpdateView):
    model = Collector
    fields = ['name', 'vessel']

class CollectorDelete(DeleteView):
    model = Collector
    success_url = '/collectors/'

def assoc_collector(Request, fish_id, collector_id):
    Fish.objects.get(id=fish_id).collectors.add(collector_id)
    return redirect('detail', fish_id=fish_id)
        # redirect to detail refers to the url path named 'detail'
        # rdirect needs two params: the url and the ID, if there is one to pass

fishcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About the Fish Collector</h1>
<hr/>
<p>Hire the Fish Collector</p>
{% endblock %}

fishcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Fish Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper cyan darken-4">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;FishCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about-us">About</a></li>
          <li><a href="{% url 'fish_create' %}">Add a Fish</a></li>
          <li><a href="{% url 'collectors_create' %}">Add a Collector</a></li>
          <li><a href="/fish">View All My Fish</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>

</body>
</html>

fishcollector/main_app/templates/fish/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Fish Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
            <span class="card-title">{{ fish.name }}</span>
            <p>Common Name: {{ fish.commonName }}</p>
            <p>Description: {{ fish.sciName }}</p>
            <p>Habitat: {{ fish.habitat }}</p>
            {% if fish.quantity > 0 %}
                <p>Quantity: {{ fish.quantity }}</p>
            {% endif %}
            </div>
            <div class="card-action">
                <a class = "deep-orange-text text-darken-4" href="{% url 'fish_update' fish.id %}">Edit</a>
                <a class = "deep-orange-text text-darken-4" href="{% url 'fish_delete' fish.id %}">Delete</a>
            </div>
        </div>
    </div>

    <div class="col s6">

        <form action = "{% url 'add_survey' fish.id %}" method="POST">
          {% csrf_token %}
          {{ survey_form.as_p }}
          <input type="submit" class="btn cyan darken-4" value="Add Survey">
        </form>
    
        <table class="striped">
          <thead>
            <tr><th>Date</th><th>Age</th></tr>
          </thead>
          <tbody>
            {% for survey in fish.surveys_set.all %}
              <tr>
                <td>{{survey.date}}</td>
                <td>{{survey.get_age_display}}</td>
              </tr>>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>

<hr>
  <div class="row">
    <div class="col s6">
        <h3>Selected Collectors</h3>
          {% if fish.collectors.count %}
              {% for collector in fish.collectors.all %}
                  <div class="card">
                      <div class="card-content">
                          <span class="card-title">
                            {{ collector.name }} on {{ collector.vessel }}
                          </span>
                      </div>
                  </div>
              {% endfor %}
          {% else %}
              <h5>No collectors have been assigned to this collection yet</h5>
          {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Collectors</h3>
        {% if collectors.count %}
          {% for collector in collectors.all %}
            <div class="card">
              <div class="card-content">
                <span class="card-title">
                  {{ collector.name }} on {{ collector.vessel }}
                </span>
              </div>
              <div class="card-action">
                <form action="{% url 'assoc_collector' fish.id collector.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn cyan darken-4">Add</button>
                </form>
              </div>
            </div>
          {% endfor %}
        {% else %}
            <h5>{{ cat.name }} All Collectors Participated in this Collection</h5>
        {% endif %}
    </div>
  </div>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
    const selectEl = document.getElementById('id_age');
      M.FormSelect.init(selectEl);
  </script>
{% endblock %}

fishcollector/main_app/templates/fish/index.html
{% extends 'base.html' %}
{% block content %}
<h1> Fish List</h1>

{% for fish in fish %}

<a href="{% url 'detail' fish.id %}">
  <div class="card">
    <div class="card-content cyan-text text-darken-4">
      <span class="card-title">{{ fish.name }}</span>
      <p>Common Name: {{ fish.commonName }}</p>
      <p>Description: {{ fish.sciName }}</p>
      <p>Habitat: {{ fish.habitat }}</p>
      {% if fish.quantity > 0 %}
        <p>Quantity: {{ fish.quantity }}</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}

fishcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Home</h1>
{% endblock %}

fishcollector/main_app/templates/main_app/collector_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Delete Collector</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'collectors_detail' object.id %}">Cancel</a>
    </form>
{% endblock %}

fishcollector/main_app/templates/main_app/collector_detail.html
{% extends 'base.html' %}
{% block content %}

    <h1>Collector Details</h1>

    <div class="row">
        <div class="col s6 col-offset-3">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Name: {{ collector.name }}</span>
                    <p>Vessel: {{ collector.vessel }}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'collectors_update' collector.id %}">Edit</a>
                    <a href="{% url 'collectors_delete' collector.id %}">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

fishcollector/main_app/templates/main_app/collector_form.html
{% extends 'base.html' %}

{% block content %}

        <h1>Add Collector</h1>

    <!-- Leaving the action empty makes the form post to the same url used to display it -->
    <form action="" method="post">
        <!-- Django requires the following for security purposes -->
        {% csrf_token %}
        <table>
            <!-- Render the inputs inside of <tr>s & <td>s -->
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn cyan darken-4">
    </form>

{% endblock %}

fishcollector/main_app/templates/main_app/collector_list.html
{% extends 'base.html' %}
{% block content %}

    <h1>Collector List</h1>

    {% for toy in collector_list %}
        <a href="{% url 'collectors_detail' collector.id %}">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Name: {{ collector.name }}</span>
                    <p>Vessel: {{ collector.vessel }}</p>
                </div>
            </div>
        </a>
    {% endfor %}

{% endblock %}

fishcollector/main_app/templates/main_app/fish_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Fish</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' fish.id %}">Cancel</a>
  </form>
{% endblock %}

fishcollector/main_app/templates/main_app/fish_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Add Fish</h1>

  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn cyan darken-4">
  </form>
  
{% endblock %}